### ISSUE TITLE
GOG

### ISSUE THREAD

**Issue by Haze2910** [MPihlap/DOS2-Mod-Updater#1]
Is it possible to make it work on GOG, I tried adding the executable as for steam (following [this](https://support.gog.com/hc/en-us/articles/360013424697-How-to-set-Launch-parameters-for-game?product=gog)) but it doesn't start.

**Comment by MPihlap** [comment]
Hi! 
I've never used GOG but we can certainly try. Can you show exactly what you did? The article you linked shows two different methods, I'd be interested to see what you entered exactly and where.

**Comment by MPihlap** [comment]
Closed due to lack of interest from issue opener.
